### ISSUE TITLE
broken submodule with fmriprep

### ISSUE THREAD

**Issue by lunebellec** [courtois-neuromod/cneuromod.processed#2]
It seems like the preprocessing repo has been renamed but the submodules have not.

https://github.com/courtois-neuromod/cneuromod.fmriprep goes to https://github.com/courtois-neuromod/fmriprep/

But this does not redirect the submodules link.

**Comment by bpinsard** [comment]
This is super weird! This is covered in the CI tests and passes. Can you add the command you are using, and the error messages, as well as the datalad version you are using? Thanks!

**Comment by lunebellec** [comment]
I navigated the repos through the github repos on my phone (firefox)

**Comment by lunebellec** [comment]
the bug does not appear on a computer. This seems to be phone specific, and may be more a problem with github than us.

**Comment by bpinsard** [comment]
Reproducible in chrome with developer tool. There is a second hidden link for submodules which weirdly point to `repo_url/tree/.`. It is not clickable in the desktop browser but magically becomes clickable in a phone browser.
The fact it points to `tree/.`  arise from the submodule being configured to track the same branch as the parent repo. ( eg. https://github.com/courtois-neuromod/cneuromod/blob/main/.gitmodules#L5 ) 
Definitely a GH issue, and I think it won't be a problem for our users, though this issue will document the glitch.
